### ISSUE TITLE
coz

### ISSUE THREAD

**Issue by piouzumaki** [lgiacomazzo/SGHD-ITA#1]
hanno rilasciato un'aggiornamento quelli dei coz e la patch italiana non funziona più...

**Comment by lgiacomazzo** [comment]
Ciao, ho visto che hanno aggiornato la patch di Steins;Gate 0, non di Steins;Gate (quindi l'issue non sarebbe di questo repo, ma dell'altro). In ogni caso, sono sicuro di quale sia il problema. Ti faccio sapere.

**Comment by piouzumaki** [comment]
per ora ho lasciato la patch non aggiornata quindi funziona!

Il giorno mer 27 apr 2022 alle ore 22:32 lgiacomazzo <
***@***.***> ha scritto:

**Comment by lgiacomazzo** [comment]
Ok, vorrei caricare qui la correzione, ma non me lo lascia fare, quindi ecco cosa devi fare:
Dopo aver scaricato la loro patch (cosa che hai già fatto), copia la mia traduzione. Poi apri il file languagebarrier/patchdef.json dentro la directory del gioco, e cerca
`  
"patchName": "[CoZ] STEINS;GATE 0 Steam Patch (2.1.1)",
"patchVersion": "2.1.1",
`
Rimpiazzali con 
`
"patchName": "[CoZ] STEINS;GATE 0 Steam Patch (2.1.2)",
"patchVersion": "2.1.2",
`
e dovrebbe funzionare tutto. Fammi sapere se è tutto ok.

Edit: ecco il file dentro lo zip (se non vuoi modificare a mano).
[fix_SG0_2.1.2.zip](https://github.com/lgiacomazzo/SGHD-ITA/files/8577829/fix_SG0_2.1.2.zip)

**Comment by piouzumaki** [comment]
si ha funzionato gentilissimo! io sono un fan delle sciadv e volevo sapere se arriverà in futuro una traduzione per robotics notes elite....in che modo si potrebbe tradurre quella novel? con che programma?

**Comment by lgiacomazzo** [comment]
Per i tool, di recente ho forkato i repo usati dai CoZ per caricare le versioni leggermente modificate che ho usato io, e sono essenzialmente 3:

- sc3tools (traduzione testi)
- ungelify (unpacking/packing file mpk, gli archivi insomma)
- mgsfontgen-dx (font)

Credo che la struttura dei file non sia diversa da quella di Steins;Gate e Steins;Gate 0, quindi penso che si possano utilizzare senza problemi (anche se bisogna capire un minimo come usarli, per esempio sc3tools e mgsfontgen-dx usano due charset diversi, e per inserire le lettere accentate in Steins;Gate ho dovuto modificare entrambi).

Sinceramente non so se voglio tradurre anche Robotic;Notes Elite, visto che ero interessato più a Steins;Gate (grazie agli anime) che al mondo delle SciAdv in generale, e poi di Robotic;Notes non so molto. Mai dire mai però, voglio comunque scaricarlo e giocarmelo prima o poi 😄

**Comment by piouzumaki** [comment]
senti ma hai fatte altre patch ita anche per le altre sciadv?

Il giorno mer 27 apr 2022 alle ore 22:57 lgiacomazzo <
***@***.***> ha scritto:

**Comment by piouzumaki** [comment]
ho visto ora scusa, volevo chiederti una cosa farai altre patch italiane
per ad esempio robotics notes?

Il giorno mer 27 apr 2022 alle ore 22:57 lgiacomazzo <
***@***.***> ha scritto:

**Comment by lgiacomazzo** [comment]
Ciao, al momento non è nelle mie intenzioni, forse in futuro, ma all'80% ti direi no.

Edit: per Chaos;Head Noah è in sviluppo una traduzione da parte dello staff di "Open the Steins Gate", per il resto non so se qualcuno stia sviluppando una traduzione oppure no.

**Comment by piouzumaki** [comment]
Salve, il progetto di open sembra droppato, non stanno piu andando avanti, tu hai intenzione di tradurle?

**Comment by lgiacomazzo** [comment]
Ciao, al momento non credo che farò altre traduzioni. Per Chaos;Head Noah ho visto che stanno andando avanti, quindi forse faranno anche gli altri titoli. Se in futuro avrò la voglia di tradurre qualcosa, vedrò se loro o qualcun altro sono attivi, e deciderò di conseguenza.

**Comment by piouzumaki** [comment]
se vuoi rimanere sempre su steins, i coz stanno lavorando alla patch per
Linear, é una vn importante quella a differenza di my darling embrance

Il giorno ven 30 giu 2023 alle ore 20:57 lgiacomazzo <
***@***.***> ha scritto:

**Comment by lgiacomazzo** [comment]
Magari aspetto che prima la completino (le traduzioni che ho fatto hanno alla base la loro patch), ma il fatto che l'acquisto di Linear su Steam sia legato a Steins;Gate Elite (che detto francamente non mi interessa) mi dà un po' di fastidio.
Vedrò in futuro, ma non ora (anche perché ho già fatto i miei acquisti su steam per questa stagione).
